trigger:
  branches:
    include:
      - main

pool:
  name: 'Default'

steps:
  - checkout: self

  # Install Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: "Install Node.js"

  # Install Dependencies
  - script: |
      cd sample_app
      npm install
    displayName: "Install NPM packages"

  # Archive application
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: 'sample_app'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    displayName: "Package application"

  # Publish artifact
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
    displayName: "Publish App Artifact"
